server:
  port: 8080
  shutdown: graceful

spring:
  application.name: practice-spring-boot
  datasource:
    reader:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/practice;AUTO_SERVER=TRUE
      username: sa
      password:
      maximum-pool-size: 30
      connection-timeout: 30000
      max-lifetime: 900000
    writer:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/practice;AUTO_SERVER=TRUE
      username: sa
      password:
      maximum-pool-size: 30
      connection-timeout: 30000
      max-lifetime: 900000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
